_wandb:
    value:
        cli_version: 0.21.0
        e:
            unw3kuw9uclopaznnbmyusdeo0bebuah:
                args:
                    - --batch_size_per_gpu
                    - "8"
                    - --gradient_accumulation_steps
                    - "2"
                    - --i_print
                    - "1"
                    - --i_log
                    - "10"
                    - --i_save
                    - "1000"
                    - --wandb
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 48
                cpu_count_logical: 95
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "942910771200"
                        used: "747542904832"
                email: yhyun225@gmail.com
                executable: /home/yhyun225/anaconda3/envs/birf/bin/python3.10
                git:
                    commit: b91adeabbda7173eecf755c7677367a3e38f57b3
                    remote: https://github.com/yhyun225/BiRF.git
                gpu: NVIDIA H100 PCIe
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 14592
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 PCIe
                      uuid: GPU-254ca72f-03d6-dc62-49fc-3c2aff963eaa
                    - architecture: Hopper
                      cudaCores: 14592
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 PCIe
                      uuid: GPU-bfb9f85b-e4e7-8a55-dfeb-21c4a0ff782d
                host: H100
                memory:
                    total: "540656336896"
                os: Linux-5.15.0-119-generic-x86_64-with-glibc2.31
                program: /home/yhyun225/BiRF/main.py
                python: CPython 3.10.18
                root: /home/yhyun225/BiRF
                startedAt: "2025-07-09T10:52:12.269452Z"
                writerId: unw3kuw9uclopaznnbmyusdeo0bebuah
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 98
            "3":
                - 61
            "4": 3.10.18
            "5": 0.21.0
            "6": 4.53.1
            "12": 0.21.0
            "13": linux-x86_64
dataloader:
    value:
        drop_last: true
        num_workers: null
        persistent_workers: true
        pin_memory: true
        shuffle: true
logit_mean:
    value: 0
logit_std:
    value: 1
mode_scale:
    value: 1.29
model:
    value:
        cache_dir: /hdd/yhyun225/cache
        lora:
            dropout: 0
            layers: null
            rank: 4
        pretrained_model_name_or_path: stabilityai/stable-diffusion-3-medium-diffusers
optimizer:
    value:
        beta1: 0.9
        beta2: 0.999
        epsilon: 1e-08
        learning_rate: 0.0001
        lr_num_cycles: 1
        lr_power: 1
        lr_scheduler: constant
        lr_warmup_steps: 500
        weight_decay: 0.0001
weighting_scheme:
    value: logit_normal
